DROP TABLE PDX_ECON.EARNINGS_EMPLOYMENT_JOIN IF EXISTS;
CREATE MEMORY TABLE PDX_ECON.EARNINGS_EMPLOYMENT_JOIN as (
SELECT ea.MONTH as PDX_MONTH, emp.UNEMPLOYMENT_RATE, ea.MANUFACTURING, ea.CONSTRUCTION, ea.LEISURE_HOSPITALITY, ea.FINANCIAL, ea.TRADE_TRANSPORT_UTILITY, ea.SERVICES_EDUCATION_HEALTH, ea.INFORMATION, ea.SERVICES_PROFESSIONAL_BUSINESS, ea.GOVERNMENT, ea.OTHER
FROM PDX_ECON.EARNINGS_PORTLAND as ea
LEFT JOIN PDX_ECON.EMPLOYMENT_PORTLAND as emp
ON ea.MONTH = emp.MONTH
ORDER BY ea.MONTH desc
);

-- SELECT * FROM PDX_ECON.EARNINGS_EMPLOYMENT_JOIN;

DROP TABLE PDX_ECON.EARNINGS_EMPLOYMENT_YOY IF EXISTS;
CREATE MEMORY TABLE PDX_ECON.EARNINGS_EMPLOYMENT_YOY as (
SELECT PDX_MONTH, UNEMPLOYMENT_RATE, (UNEMPLOYMENT_RATE - LAG(UNEMPLOYMENT_RATE, 12) OVER (ORDER BY PDX_MONTH)) as YOY_DIFF
FROM PDX_ECON.EARNINGS_EMPLOYMENT_JOIN
);

SELECT * FROM PDX_ECON.EARNINGS_EMPLOYMENT_YOY;
